### PR TITLE
Adding python 3.12 support

### PR DESCRIPTION
**Pull request by JoOkuma**

### CODE REVIEW

**Comment by JoOkuma** [comment]
Python 3.12 doesn't seem supported by all packages today

**Comment by ilan-theodoro** [comment]
@JoOkuma Do you need to pin numba?

**Comment by JoOkuma** [comment]
@ilan-theodoro, we had to do that at some point; they are always a bit behind the standard Numpy/python.
It might be time to bump every package to its latest and fix the problems.

I'm going to try to upload `python-mip` to conda. If that works, I think ultrack will be ready for `conda`, and we could use it in the CI.

Hopefully, that solves our broken CIs, and we can do this version bump with some peace of mind.

**Comment by JoOkuma** [comment]
Done through #130

**Pull request closed without merging**
