### PR TITLE
Relaxing dependencies and moving to Hatch and Pixi

### PR DESCRIPTION
**Pull request by JoOkuma**
@ilan-theodoro I broke your API when updating `pydantic` could you take a look at it?
I could not figure it out, it seems a `fastapi` problem.

### CODE REVIEW

**Comment by JoOkuma** [comment]
I'm waiting for higra to support numpy 2.0.0, https://github.com/higra/Higra/pull/277

**Comment by JoOkuma** [comment]
@ilan-theodoro I changed the CLI a bit. The config could be optional; we generate a template, and they modify it.

**Comment by JoOkuma** [comment]
I also included additional changes to close other bugs, hehe, sorry.

**Comment by JoOkuma** [comment]
@ilan-theodoro could you review this PR?

**Comment by ilan-theodoro** [comment]
lgtm!

I just think that we need to submit an issue remembering us to update our `pydantic` models to `2.*`, what do you think?

**Comment by JoOkuma** [comment]
Probably the last one, @ilan-theodoro. Do you think the Windows error is related to the "server" test?
I assume it isn't because of the "terminate/join".

**Comment by ilan-theodoro** [comment]
@JoOkuma it was. The problem is that it got killed trying to remove a sqlite db that was open somewhere. I fixed that with an empty try-catch on the removal procedure

**Comment by JoOkuma** [comment]
@ilan-theodoro, thanks; we can fix it later.

**Pull request merged**
